### ISSUE TITLE
Crash on large DB

### ISSUE THREAD

**Issue by greenozon** [christianhelle/sqlcequery#28]
App is not able to open up big DBs (> 1 GB)
prints error

**Comment by greenozon** [comment]
any updates ? :)

**Comment by christianhelle** [comment]
@greenozon  This issue unfortunately got completely forgotten... Sorry about that.

I'll re-visit this again but I could use some more specifics

- What error exactly is printed out? 
- What causes the error? Does it crash upon startup? Is it when you browse the table data? or is it from querying data? 
- How big is the database? Size on disk, table count

Are you willing to share the database so I can use it for debugging?

**Comment by christianhelle** [comment]
I'm working on a x64 build of the tool and that should help with the `OutOfMemoryExceptions` when working with large tables. I'm testing on the Northwind database example from Microsoft that I populated with a ton of products so it takes up 4GB of disk space

Enabling very large GC objects from the appSettings and running in x64 works but loading Table Data is very slow with much data

**Comment by greenozon** [comment]
Good question! I don't know which one the tool is using under the hood...

![image](https://user-images.githubusercontent.com/765343/229705033-63e4b200-608e-4aa8-8036-569e2576e493.png)

Disclamaier is a good idea

**Comment by christianhelle** [comment]
It would say in the **Database Information** tree on the left side of the application

![image](https://user-images.githubusercontent.com/710400/229731641-d9efec11-e787-481e-baf2-19256989f5d7.png)

![image](https://user-images.githubusercontent.com/710400/229731679-0e1ef035-9850-45cd-8fd7-a46b956a11ad.png)

![image](https://user-images.githubusercontent.com/710400/229731659-542d6302-becb-4103-940d-1c5728a0587a.png)

**Comment by christianhelle** [comment]
@greenozon can you try out the x64 artifacts from [this build](https://github.com/christianhelle/sqlcequery/actions/runs/4672723438)

**Comment by christianhelle** [comment]
I'll add them here as well for the sake of history since build artifacts will eventually expire

[Binaries (x64).zip](https://github.com/christianhelle/sqlcequery/files/11207911/Binaries.x64.zip)
[Installer (x64).zip](https://github.com/christianhelle/sqlcequery/files/11207915/Installer.x64.zip)

**Comment by christianhelle** [comment]
This should be fixed in [v1.3.3](https://github.com/christianhelle/sqlcequery/releases/tag/1.3.3)

**Comment by greenozon** [comment]
Thanks a lot! I"m a bit busy these days so will give it a test try soon
kudos!
