### ISSUE TITLE
About window: broken link

### ISSUE THREAD

**Issue by greenozon** [christianhelle/sqlcequery#36]
This one:
![image](https://user-images.githubusercontent.com/765343/229704691-73b22c56-3e60-4956-b92c-f6318ba1c22b.png)

==>

![image](https://user-images.githubusercontent.com/765343/229704852-36ef4a42-209a-45c1-9913-337296e2d4f6.png)

I suggest using this GH site instead....

**Comment by christianhelle** [comment]
Thanks for reporting this @greenozon 

This has a very old code base and I don't think I've been in the About page in the past decade!
