### ISSUE TITLE
Command line support

### ISSUE THREAD

**Issue by greenozon** [christianhelle/sqlcequery#40]
Hi!
does the tool support command line options?
Would be nice to for example open up a sdf and specify a password from command line...
maybe other features

**Comment by christianhelle** [comment]
@greenozon thanks for taking the time to suggest this

I have thought of this many many years ago but because SQLCE is no longer part of my daily life, I haven't really pulled myself together to build CLI tool support.

I can't promise that I'll build this, but I'm not saying no either

**Comment by christianhelle** [comment]
This tool was written in 2008 and started out as a learning project for WPF. I never really got to modernizing it is always a bit toe-cringing to work in the code base

Excuses, excuses, excuses...

**Comment by greenozon** [comment]
Wow, @christianhelle 
but your tool already has got support for command line argument!
it does support specifying the DB file!
the only question is then how to specify the password in command line once the DB is pass-protected...

**Comment by greenozon** [comment]
Are you accepting PRs? I've one small idea about the above idea
changes would be minimalistic...

**Comment by christianhelle** [comment]
@greenozon Yes, I definitely accept pull requests. If you have concrete ideas that will make your life easier, then let's get it in.

I think the command line argument is to support "Open With" in Windows

**Comment by christianhelle** [comment]
@greenozon Would a fully functioning command line version be interesting?

I use something called [Spectre.Console](https://spectreconsole.net/) in other projects, its basically a CLI argument parsing library on steroids, where you can show fancy tabular data from a CLI app

![image](https://github.com/christianhelle/sqlcequery/assets/710400/f0186395-a6cc-44bf-b997-25679014d35a)

**Comment by greenozon** [comment]
Yeah, ideally CLI should support each & every (ro widely used) functinolity of the GUI
that is yet another effort, big one I guess...
as you see my intentino was minimalistic one :)

**Comment by christianhelle** [comment]
I'll create a release with your PR and consider the full-blown CLI feature to a future point

**Comment by christianhelle** [comment]
@greenozon your contributions are now released in [v1.3.4](https://github.com/christianhelle/sqlcequery/releases/tag/1.3.4)

**Comment by greenozon** [comment]
Feel free to close this issue as I originally ment only opening up the DB from CLI...
